import { describe, it, expect } from "vitest";
import { renderHook } from "@testing-library/react";
import { I18nextProvider } from "react-i18next";
import type { ReactNode } from "react";
import { i18n } from "@/i18n";
import type { QueryResult } from "@/contracts";
import type { ReportDefinition } from "@/contracts/report-definition";
import { toCsv } from "./csv";
import { resultToAoa } from "./xlsx";
import { useExportResult } from "./useExportResult";

const wrapper = ({ children }: { children: ReactNode }) => (
  <I18nextProvider i18n={i18n}>{children}</I18nextProvider>
);

/**
 * What the engine hands over: the metric column is labelled after its own alias, because
 * `engine.ts` writes `metric.label ?? key` and knows nothing about human overrides.
 */
const result = {
  columns: [
    { key: "province", label: "استان", type: "string", isMetric: false },
    { key: "sum_amount", label: "sum_amount", type: "number", isMetric: true },
  ],
  rows: [{ province: "Tehran", sum_amount: 500 }],
  total: 1,
} as unknown as QueryResult;

const def = {
  id: "r1",
  dataset: "sales",
  columns: [],
  groupBy: [{ field: "province" }],
  metrics: [{ field: "amount", aggregation: "sum", alias: "sum_amount" }],
  presentation: { views: [] },
} as unknown as ReportDefinition;

const resolved = (d: ReportDefinition) =>
  renderHook(() => useExportResult(d, result), { wrapper }).result.current!;

describe("exports carry the labels the screen shows", () => {
  it("a renamed series reaches the CSV header", async () => {
    await i18n.changeLanguage("fa");
    const renamed = {
      ...def,
      labelOverrides: { sum_amount: { "fa-IR": "فروش خالص" } },
    } as unknown as ReportDefinition;

    // The bug this closes: the chart said «فروش خالص» and the spreadsheet said `sum_amount`.
    expect(toCsv(result)).toContain("sum_amount");
    expect(toCsv(resolved(renamed))).toContain("فروش خالص");
    expect(toCsv(resolved(renamed))).not.toContain("sum_amount");
  });

  it("a renamed series reaches the Excel header row", async () => {
    await i18n.changeLanguage("fa");
    const renamed = {
      ...def,
      labelOverrides: { sum_amount: { "fa-IR": "فروش خالص" } },
    } as unknown as ReportDefinition;

    expect(resultToAoa(resolved(renamed))[0]).toEqual(["استان", "فروش خالص"]);
  });

  // Worth having even with no override: the composed name is what the chart shows, so an export that
  // still said `sum_amount` would disagree with the screen on every report ever generated by the AI.
  it("uses the composed name when nobody has renamed anything", async () => {
    await i18n.changeLanguage("fa");
    expect(resultToAoa(resolved(def))[0]).toEqual(["استان", "مجموع درآمد"]);

    await i18n.changeLanguage("en");
    expect(resultToAoa(resolved(def))[0]).toEqual(["Province", "Sum Revenue"]);
  });

  it("follows the language, so an English reader exports English headers", async () => {
    const renamed = {
      ...def,
      labelOverrides: { sum_amount: { "fa-IR": "فروش خالص" } },
    } as unknown as ReportDefinition;

    await i18n.changeLanguage("en");
    // No English override — the composed name, not someone else's Persian.
    expect(resultToAoa(resolved(renamed))[0]).toEqual(["Province", "Sum Revenue"]);
  });

  it("leaves the rows alone — only the header changes", async () => {
    await i18n.changeLanguage("fa");
    const out = resolved(def);
    expect(out.rows).toEqual(result.rows);
    expect(out.total).toBe(result.total);
    expect(out.columns.map((c) => c.key)).toEqual(["province", "sum_amount"]);
  });
});
